config/routes.rb
StaunchRobots::Application.routes.draw do

  devise_for :users

  resources :user, only: [:show, :edit, :update]
  resources :products, only: [:index]
  resources :carts, only: [:show] do
    get :clear, on: :collection
  end
  resources :cart_items, only: [:create, :destroy]

  resources :categories do
    resources :products
  end

  namespace :admin do
    resources :products, :categories, :users
  end

  match '/cart' => 'carts#show', as: :cart
  match '/about' => 'categories#about_us', as: :about
  match '/admin' => 'admin/categories#index', as: :admin

  root to: 'categories#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :color

  has_many :products

  validates_presence_of :name, :color
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  # GET /admin/categories
  # GET /admin/categories.json
  def index
    @admin_categories = Category.order("name").page(params[:page]).per_page(20)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_categories }
    end
  end

  # GET /admin/categories/1
  # GET /admin/categories/1.json
  def show
    @admin_category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_category }
    end
  end

  # GET /admin/categories/new
  # GET /admin/categories/new.json
  def new
    @admin_category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_category }
    end
  end

  # GET /admin/categories/1/edit
  def edit
    @admin_category = Category.find(params[:id])
  end

  # POST /admin/categories
  # POST /admin/categories.json
  def create
    @admin_category = Category.new(params[:category])

    respond_to do |format|
      if @admin_category.save
        format.html { redirect_to [:admin, @admin_category], notice: 'Category was successfully created.' }
        format.json { render json: @admin_category, status: :created, location: @admin_category }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/categories/1
  # PUT /admin/categories/1.json
  def update
    @admin_category = Category.find(params[:id])
    @admin_category.assing_attributes(params[:category])

    respond_to do |format|
      if @admin_category.save
        format.html { redirect_to [:admin, @admin_category], notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/categories/1
  # DELETE /admin/categories/1.json
  def destroy
    @admin_category = Category.find(params[:id])
    @admin_category.destroy

    respond_to do |format|
      format.html { redirect_to admin_categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :index, :about_us]
  before_filter :random_products, only: [:index]

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @category_products = @category.products.where("qty > 0")
  end

  def about_us
  end

  private

    def random_products
      @random_products = Product.where("qty > 0").limit(5).order("random()")
    end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def category_list
    Category.order("name")
  end
end

app/views/admin/categories/_form.html.erb
<div class="well">
  <div class="row">
    <div class="span6 offset3">

      <%= simple_form_for [:admin, @admin_category] do |f| %>
        <div class"alert alert-error">
          <%= f.error_notification %>
        </div>

        <fieldset class="control-group-error">
          <%= f.input :name %>
          <%= f.input :color %>
        </fieldset>

          <div class="center">
            <%= f.button :submit, class: "btn btn-primary" %>
          </div>
        <% end %>

    </div>
  </div>
</div>

app/views/admin/categories/edit.html.erb
<h1>Edit Category</h1>

<%= render 'form' %>

<div class="center">
  <%= link_to 'Show', [:admin, @admin_category], class: "btn btn-primary" %> |
  <%= link_to 'Back', admin_categories_path, class: "btn btn-primary" %>
</div>

app/views/admin/categories/index.html.erb
<h1>List of Categories</h1>

<div class="center">
  <%= will_paginate @admin_categories %>
</div>

<table class="table table-striped table-bordered">
  <tr>
    <th>Name</th>
    <th>Color</th>
    <th colspan="3" style="text-align:center;">Actions</th>
  </tr>

<% @admin_categories.each do |admin_category| %>
  <tr>
    <td><%= admin_category.name %></td>
    <td><%= admin_category.color %></td>
    <td><%= link_to 'Show', [:admin, admin_category], class: "btn btn-primary" %></td>
    <td><%= link_to 'Edit', edit_admin_category_path(admin_category), class: "btn btn-primary" %></td>
    <td><%= link_to 'Destroy', [:admin, admin_category], confirm: 'Are you sure?', method: :delete, class: "btn btn-danger" %></td>
  </tr>
<% end %>
</table>

<div class="center">
  <%= will_paginate @admin_categories %>
  <br />
  <%= link_to 'New Category', new_admin_category_path, class: "btn btn-primary"  %>
</div>

<br />

app/views/admin/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<div class="center">
  <%= link_to 'Back', admin_categories_path, class: "btn btn-primary" %>
</div>

app/views/admin/categories/show.html.erb
<h1>Category Details</h1>

<div class="well">
  <div class="row">
    <div class="span6 offset3">

     <table class="table table-bordered">
        <tr>
          <td><b>Name:</b></td>
          <td><%= @admin_category.name %></td>
        </tr>

        <tr>
          <td><b>Color:</b></td>
          <td><%= @admin_category.color %></td>
        </tr>
      </table>

      <div class="center">
        <%= link_to 'Edit', edit_admin_category_path(@admin_category), class: "btn btn-primary" %> |
        <%= link_to 'Back', admin_categories_path, class: "btn btn-primary" %>
      </div>

    </div>
  </div>
</div>