config/routes.rb
StaunchRobots::Application.routes.draw do

  devise_for :users

  resources :user, only: [:show, :edit, :update]
  resources :products, only: [:index]
  resources :carts, only: [:show] do
    get :clear, on: :collection
  end
  resources :cart_items, only: [:create, :destroy]

  resources :categories do
    resources :products
  end

  namespace :admin do
    resources :products, :categories, :users
  end

  match '/cart' => 'carts#show', as: :cart
  match '/about' => 'categories#about_us', as: :about
  match '/admin' => 'admin/categories#index', as: :admin

  root to: 'categories#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  extend FriendlyId
  friendly_id :album, use: :slugged

  has_attached_file :picture,
                    styles: { small: "176x176>", big: "500x500>" },
                    path: ":rails_root/public/system/:attachment/:id/:style/:filename",
                    url: "/system/:attachment/:id/:style/:filename"

  attr_accessible :album, :artist, :description, :qty, :price, :on_sale, :sale_price, :category_id, :picture

  belongs_to :category
  has_many :cart_items
  has_many :carts, through: :cart_items

  validates_presence_of   :album, :artist, :category_id, :qty, :price
  validates :qty,         numericality: { greater_than_or_equal_to: 0 }
  validates :price,       numericality: { greater_than: 0 }
  validates :category_id, numericality: { greater_than: 0 }
  validates :sale_price,  numericality: { greater_than: 0, less_than_or_equal_to: :price }
  validates :on_sale ,    inclusion: { in: [true, false] }
  validates_attachment_size  :picture, in: 0..2.megabytes

  searchable do
    text :album, :artist, :description
  end

  def total
    on_sale ? sale_price : price
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  # GET /admin/products
  # GET /admin/products.json
  def index
    @admin_products = Product.order("album").page(params[:page]).per_page(20)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_products }
    end
  end

  # GET /admin/products/1
  # GET /admin/products/1.json
  def show
    @admin_product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_product }
    end
  end

  # GET /admin/products/new
  # GET /admin/products/new.json
  def new
    @admin_product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_product }
    end
  end

  # GET /admin/products/1/edit
  def edit
    @admin_product = Product.find(params[:id])
  end

  # POST /admin/products
  # POST /admin/products.json
  def create
    @admin_product = Product.new(params[:product])

    respond_to do |format|
      if @admin_product.save
        format.html { redirect_to [:admin, @admin_product], notice: 'Product was successfully created.' }
        format.json { render json: @admin_product, status: :created, location: @admin_product }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/products/1
  # PUT /admin/products/1.json
  def update
    @admin_product = Product.find(params[:id])
    @admin_product.assign_attributes(params[:product])

    @admin_product.valid?
    Rails.logger.info '!!!!!!!!'
    Rails.logger.info @admin_product.errors.inspect


    respond_to do |format|
      if @admin_product.save
        format.html { redirect_to [:admin, @admin_product], notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/products/1
  # DELETE /admin/products/1.json
  def destroy
    @admin_product = Product.find(params[:id])
    @admin_product.destroy

    respond_to do |format|
      format.html { redirect_to admin_products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :get_category, except: [:index]
  before_filter :authenticate_user!, except: [:index]

  def index
    @search = Product.search do
      fulltext params[:q]
    end
    @products = @search.results if @search
  end

  def show
    @product = @category.products.find(params[:id])
  end

  private

    def get_category
      @category = Category.find(params[:category_id])
    end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<div class="well">
  <div class="row">
    <div class="span6 offset3">

      <%= simple_form_for [:admin, @admin_product], html: { :multipart => true }  do |f| %>
        <div class"alert alert-error">
          <%= f.error_notification %>
          <%= @admin_product.errors.full_messages.join(', ') %>
        </div>

        <fieldset class="control-group-error">
            <%= f.input :album %>
            <%= f.input :artist %>
            <%= f.input :description %>
            <%= f.association :category %>
            <%= f.input :qty %>
            <%= f.input :price %>
            <%= f.input :picture %>
            <%= f.input :sale_price %>
            <%= f.input :on_sale %>
        </fieldset>

        <div class="center">
          <%= f.button :submit, class: "btn btn-primary" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/admin/products/edit.html.erb
<h1>Edit Product</h1>

<%= render 'form' %>

<div class="center">
  <%= link_to 'Show', [:admin, @admin_product], class: "btn btn-primary" %> |
  <%= link_to 'Back', admin_products_path, class: "btn btn-primary" %>
</div>

app/views/admin/products/index.html.erb
<h1>List of Products</h1>

<div class="center">
  <%= will_paginate @admin_products %>
</div>

<table class="table table-striped table-bordered">
  <tr>
    <th>Album</th>
    <th>Artist</th>
    <th>Description</th>
    <th>Quantity</th>
    <th>Price</th>
    <th>On Sale</th>
    <th>Sale Price</th>
    <th>Category</th>
    <th colspan="3" style="text-align:center;">Actions</th>
  </tr>

<% @admin_products.each do |admin_product| %>
  <tr>
    <td><%= admin_product.album %></td>
    <td><%= admin_product.artist %></td>
    <td><%= admin_product.description %></td>
    <td><%= admin_product.qty %></td>
    <td><%= admin_product.price %></td>
    <% if admin_product.on_sale %>
      <td>Yes</td>
    <% else %>
      <td>No</td>
    <% end %>
    <td><%= admin_product.sale_price %></td>
    <td><%= admin_product.category_id %></td>
    <td><%= link_to 'Show', [:admin, admin_product], class: "btn btn-primary" %></td>
    <td><%= link_to 'Edit', edit_admin_product_path(admin_product), class: "btn btn-primary" %></td>
    <td><%= link_to 'Destroy', [:admin, admin_product], confirm: 'Are you sure?', method: :delete, class: "btn btn-danger" %></td>
  </tr>
<% end %>
</table>

<div class="center">
  <%= will_paginate @admin_products %>
  <br />
  <%= link_to 'New Product', new_admin_product_path, class: "btn btn-primary" %>
</div>

<br />

app/views/admin/products/new.html.erb
<%= simple_form_for([:admin, @product], :html => {:class => 'form-horizontal' }) do |f| %>
  <%= f.input :album %>
  <%= f.input :artist %>
  <%= f.association :category %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.input :qty %>
  <%= f.input :sale_price %>
  <%= f.input :on_sale %>
  <%= f.submit %>
<% end %>

app/views/admin/products/show.html.erb
<h1>Product Details</h1>

<div class="well">
  <div class="row">
    <div class="span6 offset3">

      <div class"center">
        <% if @admin_product.picture.exists? %>
          <%= image_tag @admin_product.picture.url(:small), class: "thumbnail" %>
        <% else %>
          <%= image_tag "default-product.jpg", size: "176x176" %>
        <% end %>
      </div>

      <table class="table table-bordered">
        <tr>
          <td><b>Album:</b></td>
          <td><%= @admin_product.album %></td>
        </tr>

        <tr>
          <td><b>Artist:</b></td>
          <td><%= @admin_product.artist %></td>
        </tr>

        <tr>
          <td><b>Description:</b></td>
          <td><%= @admin_product.description %></td>
        </tr>

        <tr>
          <td><b>Quantity:</b></td>
          <td><%= @admin_product.qty %></td>
        </tr>

        <tr>
          <td><b>Price:</b></td>
          <td><%= @admin_product.price %></td>
        </tr>

        <tr>
          <td><b>On sale:</b></td>
          <td>
            <% if @admin_product.on_sale %>
              Yes
            <% else %>
              No
            <% end %>
          </td>
        </tr>

        <tr>
          <td><b>Sale price:</b></td>
          <td><%= @admin_product.sale_price %></td>
        </tr>

        <tr>
          <td><b>Category:</b></td>
          <td><%= @admin_product.category_id %></td>
        </tr>
      </table>

      <div class="center">
        <%= link_to 'Edit', edit_admin_product_path(@admin_product), class: "btn btn-primary" %> |
        <%= link_to 'Back', admin_products_path, class: "btn btn-primary" %>
      </div>

    </div>
  </div>
</div>