config/routes.rb
StaunchRobots::Application.routes.draw do

  devise_for :users

  resources :user, only: [:show, :edit, :update]
  resources :products, only: [:index]
  resources :carts, only: [:show] do
    get :clear, on: :collection
  end
  resources :cart_items, only: [:create, :destroy]

  resources :categories do
    resources :products
  end

  namespace :admin do
    resources :products, :categories, :users
  end

  match '/cart' => 'carts#show', as: :cart
  match '/about' => 'categories#about_us', as: :about
  match '/admin' => 'admin/categories#index', as: :admin

  root to: 'categories#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :profile_picture,
                    styles: { medium: "300x300>", thumb: "100x100>" },
                    path: ":rails_root/public/system/:attachment/:id/:style/:filename",
                    url: "/system/:attachment/:id/:style/:filename"
  has_one :cart

  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :birthday, :country, :profile_picture, :admin

  validates_presence_of :email
  validates_uniqueness_of :email

  validates_attachment_size :profile_picture, in: 0..500.kilobytes

  validates_inclusion_of :admin, in: [true, false]
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  # GET /admin/users
  # GET /admin/users.json
  def index
    @admin_users = User.order("first_name").page(params[:page]).per_page(20)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_users }
    end
  end

  # GET /admin/users/1
  # GET /admin/users/1.json
  def show
    @admin_user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_user }
    end
  end

  # GET /admin/users/new
  # GET /admin/users/new.json
  def new
    @admin_user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_user }
    end
  end

  # GET /admin/users/1/edit
  def edit
    @admin_user = User.find(params[:id])
  end

  # POST /admin/users
  # POST /admin/users.json
  def create
    @admin_user = User.new(params[:user])

    respond_to do |format|
      if @admin_user.save
        format.html { redirect_to [:admin, @admin_user], notice: 'User was successfully created.' }
        format.json { render json: @admin_user, status: :created, location: @admin_user }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/users/1
  # PUT /admin/users/1.json
  def update
    @admin_user = User.find(params[:id])
    @admin_user.assign_attributes(params[:user])

    respond_to do |format|
      if @admin_user.save
        format.html { redirect_to [:admin, @admin_user], notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else

        format.html { render action: "edit" }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.json
  def destroy
    @admin_user = User.find(params[:id])
    @admin_user.destroy

    respond_to do |format|
      format.html { redirect_to admin_users_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_filter :authenticate_user!

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:notice] = "Profile updated"
      redirect_to root_path
    else
      render 'edit'
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/users/_form.html.erb
<div class="well">
  <div class="row">
    <div class="span6 offset3">

      <%= simple_form_for [:admin, @admin_user], html: { :multipart => true } do |f| %>
        <div class"alert alert-error">
          <%= f.error_notification %>
          <%= @admin_user.errors.full_messages.join(', ') %>
        </div>

        <fieldset class="control-group-error">
          <%= f.input :first_name %>
          <%= f.input :last_name %>
          <%= f.input :email %>
          <%= f.input :birthday %>
          <%#= f.input :country %>
          <%= f.input :profile_picture %>
          <%= f.input :admin %>
        </fieldset>

        <div class="center">
          <%= f.button :submit, class: "btn btn-primary" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/admin/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form' %>

<div class="center">
  <%= link_to 'Show', [:admin, @admin_user], class: "btn btn-primary" %> |
  <%= link_to 'Back', admin_users_path, class: "btn btn-primary" %>
</div>

app/views/admin/users/index.html.erb
<h1>List of Users</h1>

<div class="center">
  <%= will_paginate @admin_users %>
</div>

<table class="table table-striped table-bordered">
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>Birthday</th>
    <th>Country</th>
    <th>Admin</th>
    <th colspan="3" style="text-align:center;">Actions</th>
  </tr>

<% @admin_users.each do |admin_user| %>
  <tr>
    <td><%= admin_user.first_name %></td>
    <td><%= admin_user.last_name %></td>
    <td><%= admin_user.email %></td>
    <td><%= admin_user.birthday %></td>
    <td><%= admin_user.country %></td>
    <% if admin_user.admin %>
      <td>Yes</td>
    <% else %>
      <td>No</td>
    <% end %>
    <td><%= link_to 'Show', [:admin, admin_user], class: "btn btn-primary" %></td>
    <td><%= link_to 'Edit', edit_admin_user_path(admin_user), class: "btn btn-primary" %></td>
    <td><%= link_to 'Destroy', [:admin, admin_user], confirm: 'Are you sure?', method: :delete, class: "btn btn-danger" %></td>
  </tr>
<% end %>
</table>

<div class="center">
  <%= will_paginate @admin_users %>
  <br />
  <%= link_to 'New User', new_admin_user_path, class: "btn btn-primary"  %>
</div>

<br />

app/views/admin/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<div class="center">
  <%= link_to 'Back', admin_users_path, class: "btn btn-primary" %>
</div>

app/views/admin/users/show.html.erb
<h1>User Details</h1>

<div class="well">
  <div class="row">
    <div class="span6 offset3">

      <div class"center">
        <% if @admin_user.profile_picture.exists? %>
          <%= image_tag @admin_user.profile_picture.url(:thumb), class: "thumbnail" %>
        <% else %>
          <%= image_tag "default_user.png", size: "100x100", class: "thumbnail" %>
        <% end %>
      </div>

     <table class="table table-bordered">
        <tr>
          <td><b>First name:</b></td>
          <td><%= @admin_user.first_name %></td>
        </tr>

        <tr>
          <td><b>Last name:</b></td>
          <td><%= @admin_user.last_name %></td>
        </tr>

        <tr>
          <td><b>Email:</b></td>
          <td><%= @admin_user.email %></td>
        </tr>

        <tr>
          <td><b>Birthday:</b></td>
          <td><%= @admin_user.birthday %></td>
        </tr>

        <tr>
          <td><b>Country:</b></td>
          <td><%= @admin_user.country %></td>
        </tr>

        <tr>
          <td><b>Administrator:</b></td>
          <td>
            <% if @admin_user.admin %>
              Yes
            <% else %>
              No
            <% end %>
          </td>
        </tr>
      </table>

      <div class="center">
        <%= link_to 'Edit', edit_admin_user_path(@admin_user), class: "btn btn-primary" %> |
        <%= link_to 'Back', admin_users_path, class: "btn btn-primary" %>
      </div>

    </div>
  </div>
</div>