config/routes.rb
StaunchRobots::Application.routes.draw do

  devise_for :users

  resources :user, only: [:show, :edit, :update]
  resources :products, only: [:index]
  resources :carts, only: [:show] do
    get :clear, on: :collection
  end
  resources :cart_items, only: [:create, :destroy]

  resources :categories do
    resources :products
  end

  namespace :admin do
    resources :products, :categories, :users
  end

  match '/cart' => 'carts#show', as: :cart
  match '/about' => 'categories#about_us', as: :about
  match '/admin' => 'admin/categories#index', as: :admin

  root to: 'categories#index'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_many :cart_items
  has_many :products, through: :cart_items

  validates_presence_of :user_id

  # Creates a cart for a newly created user
  def self.create_user_cart(user_id)
    create(user_id: user_id)
  end

  def total
    products.to_a.sum(&:total)
  end

  def clear
    cart_items.delete_all
  end
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :cart
  belongs_to :product

  validates_presence_of :cart_id, :product_id
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :color

  has_many :products

  validates_presence_of :name, :color
end

app/models/product.rb
class Product < ActiveRecord::Base
  extend FriendlyId
  friendly_id :album, use: :slugged

  has_attached_file :picture,
                    styles: { small: "176x176>", big: "500x500>" },
                    path: ":rails_root/public/system/:attachment/:id/:style/:filename",
                    url: "/system/:attachment/:id/:style/:filename"

  attr_accessible :album, :artist, :description, :qty, :price, :on_sale, :sale_price, :category_id, :picture

  belongs_to :category
  has_many :cart_items
  has_many :carts, through: :cart_items

  validates_presence_of   :album, :artist, :category_id, :qty, :price
  validates :qty,         numericality: { greater_than_or_equal_to: 0 }
  validates :price,       numericality: { greater_than: 0 }
  validates :category_id, numericality: { greater_than: 0 }
  validates :sale_price,  numericality: { greater_than: 0, less_than_or_equal_to: :price }
  validates :on_sale ,    inclusion: { in: [true, false] }
  validates_attachment_size  :picture, in: 0..2.megabytes

  searchable do
    text :album, :artist, :description
  end

  def total
    on_sale ? sale_price : price
  end

end

app/models/product_observer.rb
class ProductObserver < ActiveRecord::Observer
  def before_update(product)
    if (product.changed_attributes.keys & ["price", "sale_price", "on_sale"]).size > 0
      notify_users_price_changed(product)
    end
  end

  def notify_users_price_changed(product)
    updated_carts = Cart.with_product(product)
    updated_carts.each do |cart|
      UserMailer.product_price_changed(cart.user, product).deliver
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :profile_picture,
                    styles: { medium: "300x300>", thumb: "100x100>" },
                    path: ":rails_root/public/system/:attachment/:id/:style/:filename",
                    url: "/system/:attachment/:id/:style/:filename"
  has_one :cart

  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :birthday, :country, :profile_picture, :admin

  validates_presence_of :email
  validates_uniqueness_of :email

  validates_attachment_size :profile_picture, in: 0..500.kilobytes

  validates_inclusion_of :admin, in: [true, false]
end

app/models/user_observer.rb
class UserObserver < ActiveRecord::Observer
  def after_create(user)
    Cart.create_user_cart(user.id)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :authenticate_admin
  layout 'admin'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def authenticate_admin
    redirect_to root_path, notice: 'You should be admin to access that' if current_user.nil? || !current_user.admin
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def create
  @cart_item = CartItem.new(product_id: params[:id], cart_id: current_user.cart.id)

    respond_to do |format|
      if @cart_item.save
        format.html { redirect_to :back, notice: 'The product was added to the cart' }
        format.json { render json: @cart_item, status: :created, location: @cart_item }
      else
        format.html { redirect_to :back, notice: 'The product could not be added to the cart' }
        format.json { render json: @cart_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy

    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_filter :authenticate_user!

  def show
    @cart = current_user.cart

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cart.products }
    end
  end

  def clear
    @cart = current_user.cart
    @cart.clear

    respond_to do |format|
      format.html { redirect_to :back, notice: 'The cart was cleared' }
      format.json { head :no_content }
    end

  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :index, :about_us]
  before_filter :random_products, only: [:index]

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @category_products = @category.products.where("qty > 0")
  end

  def about_us
  end

  private

    def random_products
      @random_products = Product.where("qty > 0").limit(5).order("random()")
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :get_category, except: [:index]
  before_filter :authenticate_user!, except: [:index]

  def index
    @search = Product.search do
      fulltext params[:q]
    end
    @products = @search.results if @search
  end

  def show
    @product = @category.products.find(params[:id])
  end

  private

    def get_category
      @category = Category.find(params[:category_id])
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_filter :authenticate_user!

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:notice] = "Profile updated"
      redirect_to root_path
    else
      render 'edit'
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def category_list
    Category.order("name")
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_footer.html.erb
<div class="footer_resize">
  <p class="center">&copy; Copyright Staunch Records <%= Date.today.year %>. A <%= link_to "Staunch Robots", 'http://staunchrobots.com' %> company. </p>
  <div class="clr"></div>
</div>

app/views/layouts/_header.html.erb
<div class="header">
  <div class="header_resize">
    <div class="logo">
      <h1><%= link_to "staunch records", root_path %></h1>
    </div>
    <!-- search -->
    <div class="searchform">
      <%= form_tag products_path(), method: :get, id: 'formsearch', name: 'formsearch' do %>
      <span>
        <%= text_field_tag 'q', params[:q], maxlength: 80, placeholder: "Search...", class: "editbox_search" %>
      </span>
        <%= image_submit_tag "search_btn.png", alt: "search", class: "button_search", name: "button_search", name: nil %>
      <% end %>
    </div>
    <!-- /search -->
    <!-- menu -->
    <div class="menu">
      <ul class="menusm">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About us", about_url %></li>
        <li><%= link_to "Categories", '#', class: "ms_top ms_havesubmenu" %>
          <ul>
            <% category_list.each do |category| %>
              <li><%= link_to category.name, category_path(category) %></li>
            <% end %>
          </ul>
        </li>
        <% if user_signed_in? %>
          <li><%= link_to "Account", user_path(current_user) %></li>
          <li><%= link_to "Cart", cart_path %></li>
          <li class="last_pos"><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
          <% else %>
            <li><%= link_to('Login', new_user_session_path)  %></li>
            <li class="last_pos"><%= link_to 'Sign up', new_user_registration_path %></li>
          <% end %>
        </li>
      </ul>
    </div>
    <!-- /menu -->
    <div class="clr"></div>
  </div>
  <div class="clr"></div>
  <div class="header_sep"></div>
  <div class="clr"></div>
</div>

app/views/layouts/_shim.html.erb
<!--[if gte IE 9]>
  <script type="text/javascript"> Cufon.set('engine', 'canvas'); </script>
<![endif]-->

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Staunch Records | Admin</title>
  <%= stylesheet_link_tag "admin/admin", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <div style="font-family: Skia, sans-serif">
        <%= link_to 'staunch records', admin_products_path, id: "logo" %>
      </div>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to 'Categories', admin_categories_path %></li>
          <li><%= link_to 'Products', admin_products_path %></li>
          <li><%= link_to 'Users', admin_users_path %></li>

        </ul>
      </nav>
    </div>
  </div>
</header>

  <div class="container">
    <div class="notice" id="notice">
      <div class"alert alert-success"><%= notice %></div>
      <div class"alert alert-error"><%= alert %></div>
    </div>

    <%= yield %>

    <footer class="footer">
      <small>
        Staunch Records
        <a href="http://staunchrobots.com">by Staunch Robots</a>
      </small>
      <nav>
        <ul>
          <li><a href="https://github.com/sebasoga/staunch_records">Source</a></li>
          <li> | </li>
          <li><a href="https://github.com/sebasoga/staunch_records/issues">Report a bug</a></li>
        </ul>
      </nav>
    </footer>
  </div>

  <script languaje="javascript">
    var data = {};
      data[compv.tools.csrf_param()] = compv.tools.csrf_token();
      $.destroy({
        url: element.attr('data-destroy-url'),
        success: mapping.success,
        data: data
      });
  </script>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Staunch Records</title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= stylesheet_link_tag    "menusm", media: "all" %>
  <%= stylesheet_link_tag    "style", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "cufon-headers_font" %>
  <%= javascript_include_tag "cufon-libsans-r-b" %>
  <%= javascript_include_tag "cufon-yui" %>
  <%= javascript_include_tag "jquery.color" %>
  <%= javascript_include_tag "menusm" %>
  <%= javascript_include_tag "scripts" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>

<body>
  <div class="main">
    <div id="main_page">
      <div class="page_index">
        <%= render 'layouts/header' %>
        <div class="content">
          <div class="clr"></div>
          <!-- now_page -->
          <div class="now_page">
            <div class="now_page_sep"></div>
            <div class="now_page_resize">
              <div class="clr"></div>
            </div>
            <div class="clr"></div>
            <div class="now_page_sep"></div>
            <div class="clr"></div>
          </div>
          <div class="clr"></div>
          <!-- /now_page -->
          <div class="content_resize">
            <div class="notice" id="notice">
              <div class"alert alert-success">
                <h2><%= notice %></h2>
              </div>
              <div class"alert alert-error">
                <h2><%= alert %></h2>
              </div>
            </div>
            <!--content_index-->
            <div class="content_index">
              <%= yield %>
            </div>
          </div>
          <div class="clr"></div>
        </div>
        <div class="clr"></div>
      </div>
      <!-- footer -->
      <div class="footer">
        <%= render 'layouts/footer' %>
      </div>
      <!-- /footer -->
    </div>
    <div class="clr"></div>
  </div>
</body>
</html>